/* DO NOT EDIT THIS FILE - it is machine generated */
//#include <jni.h>
#include "../../../../../../../SDK/ndk-bundle/sysroot/usr/include/jni.h"
/* Header for class com_lauzy_freedom_librarys_view_blur_ImageBlur */

#ifndef _Included_com_lauzy_freedom_librarys_view_blur_ImageBlur
#define _Included_com_lauzy_freedom_librarys_view_blur_ImageBlur
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lauzy_freedom_librarys_view_blur_ImageBlur
 * Method:    blurPixels
 * Signature: ([IIII)V
 */
JNIEXPORT void JNICALL Java_com_lauzy_freedom_librarys_view_blur_ImageBlur_blurPixels
  (JNIEnv *, jclass, jintArray, jint, jint, jint);

/*
 * Class:     com_lauzy_freedom_librarys_view_blur_ImageBlur
 * Method:    blurBitmap
 * Signature: (Landroid/graphics/Bitmap;I)V
 */
JNIEXPORT void JNICALL Java_com_lauzy_freedom_librarys_view_blur_ImageBlur_blurBitmap
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_lauzy_freedom_librarys_view_blur_ImageBlur
 * Method:    blurBitmapClip
 * Signature: (Landroid/graphics/Bitmap;II)V
 */
JNIEXPORT void JNICALL Java_com_lauzy_freedom_librarys_view_blur_ImageBlur_blurBitmapClip
  (JNIEnv *, jclass, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
